#include <math.h>
#include <stdio.h>
extern double boysGaussJacobi(int m, double z);
/***************************************************
* @brief compute a value with the program and compare it with a correct one.
* @param[in] m The integer index of Boys function.
* @param[in] z The argument of Boys function.
* @param[in] value The correct (expected) value.
* @param[in] errMarg A relative error margin to produce verbose output.
* @return 0 if the computed value is within 3 times the error margin.
* So this is considered a test passed.
* Otherwise 1.
*/
static int boysGaussJacobiComp(int m, double z, double value, double errMarg) {
	/* value generated by theprogram
	*/
	double F = boysGaussJacobi(m, z);
	/* relative error
	*/
	double err = fabs(1. - F / value);
	if (err > errMarg)
		printf("m=%d z=%f %.17e expected %.17e rel err %.3e\n", m, z, F, value, err);
	return (err > 3 * errMarg) ? 1 : 0;
}
/***************************************
* @brief Test main function for the boysGaussJacobi subroutine.
* For 175 pairs of m and z we compute the numerical value and
* compare it with a known result that was obtained with high precision.
* @param[in] argc Number of arguments in the command line.
* Dummy parameter. Not used.
* @param[in] argv The vector of command line arguments.
* Dummy parameter. Not used.
* @since 2017-09-17
* @author Richard J. Mathar
*/
int main(int argc, char *argv[]) {
	/* print results if the relative error in the computed value exceeds this number
	*/
	double errMarg = 1.e-15;
	int err = 0;
	/* m = 0 .. 10, z= 0.000000e+00 .. 5.000000e+00 */
	err += boysGaussJacobiComp(3, 1.10185120525508566e+00, 6.18766542175746446e-02, errMarg);
	err += boysGaussJacobiComp(2, 1.76577119262604747e+00, 6.11825639426621793e-02, errMarg);
	err += boysGaussJacobiComp(4, 3.23037524963850408e+00, 9.12059472487586327e-03, errMarg);
	err += boysGaussJacobiComp(0, 3.08608408426085971e+00, 4.97929773714634554e-01, errMarg);
	err += boysGaussJacobiComp(4, 3.22317208440663363e+00, 9.16815839139274350e-03, errMarg);
	err += boysGaussJacobiComp(1, 1.05782425556418974e+00, 1.83784360820336149e-01, errMarg);
	err += boysGaussJacobiComp(7, 1.16240645029399288e-01, 6.01724161273037453e-02, errMarg);
	err += boysGaussJacobiComp(0, 4.69364098297121447e+00, 4.08169033593379339e-01, errMarg);
	err += boysGaussJacobiComp(7, 1.67085426805529170e+00, 1.55179557273704668e-02, errMarg);
	err += boysGaussJacobiComp(5, 4.39642388637500865e+00, 2.72813318450120458e-03, errMarg);
	err += boysGaussJacobiComp(9, 4.59060542843920716e-01, 3.47709144661698761e-02, errMarg);
	err += boysGaussJacobiComp(0, 1.56064093021955635e+00, 6.54583832433497471e-01, errMarg);
	err += boysGaussJacobiComp(4, 9.11886468618789914e-01, 5.32214686889205691e-02, errMarg);
	err += boysGaussJacobiComp(1, 2.81084401770867673e+00, 8.16601636195038075e-02, errMarg);
	err += boysGaussJacobiComp(7, 2.81363558170664424e+00, 5.85296951907279933e-03, errMarg);
	err += boysGaussJacobiComp(1, 3.51776621659429321e+00, 6.24073761837337416e-02, errMarg);
	err += boysGaussJacobiComp(6, 2.54481034876241880e+00, 8.91456880247929484e-03, errMarg);
	err += boysGaussJacobiComp(2, 1.71097775420966734e-02, 1.97571934031116749e-01, errMarg);
	err += boysGaussJacobiComp(0, 2.62990041558805845e+00, 5.34555136098613369e-01, errMarg);
	err += boysGaussJacobiComp(0, 2.78853346207363049e+00, 5.21052265143433045e-01, errMarg);
	err += boysGaussJacobiComp(0, 4.93413454710710736e+00, 3.98298389255380287e-01, errMarg);
	err += boysGaussJacobiComp(3, 3.20655684117901929e+00, 1.42860523385369159e-02, errMarg);
	err += boysGaussJacobiComp(3, 6.40894462299422263e-01, 8.73622913508490626e-02, errMarg);
	err += boysGaussJacobiComp(7, 4.93617748799008009e+00, 1.01619982345831285e-03, errMarg);
	err += boysGaussJacobiComp(0, 1.18165384269143953e+00, 7.13995613900412723e-01, errMarg);
	err += boysGaussJacobiComp(7, 2.55090351987942377e+00, 7.31067587218400585e-03, errMarg);
	err += boysGaussJacobiComp(6, 1.43808078860566576e+00, 2.24575690498485180e-02, errMarg);
	err += boysGaussJacobiComp(1, 4.35417133561288676e+00, 4.71400052658071444e-02, errMarg);
	err += boysGaussJacobiComp(1, 1.67247487969853155e+00, 1.34919268673417994e-01, errMarg);
	err += boysGaussJacobiComp(6, 2.44572821278028255e-01, 6.22559783625824615e-02, errMarg);
	err += boysGaussJacobiComp(4, 2.14843573474138502e+00, 2.03351671820967326e-02, errMarg);
	err += boysGaussJacobiComp(8, 2.50113793296766264e+00, 6.47719310910455897e-03, errMarg);
	err += boysGaussJacobiComp(8, 2.01268788057210367e+00, 9.91151761669940898e-03, errMarg);
	err += boysGaussJacobiComp(3, 4.85494664062866054e+00, 5.23515888992428097e-03, errMarg);
	err += boysGaussJacobiComp(2, 4.94472597757495695e+00, 1.12662528797242100e-02, errMarg);
	/* m = 10 .. 90, z= 0.000000e+00 .. 5.000000e+00 */
	err += boysGaussJacobiComp(17, 4.12310997736165195e+00, 5.93024056274768668e-04, errMarg);
	err += boysGaussJacobiComp(28, 1.98260147027554227e-01, 1.44860444295897823e-02, errMarg);
	err += boysGaussJacobiComp(15, 2.25700445900700971e+00, 3.90584744716254340e-03, errMarg);
	err += boysGaussJacobiComp(17, 2.15090246014902853e+00, 3.75932258163156043e-03, errMarg);
	err += boysGaussJacobiComp(14, 1.25940467381241843e+00, 1.06475929028584714e-02, errMarg);
	err += boysGaussJacobiComp(55, 3.00725393541662858e+00, 4.70297867669921504e-04, errMarg);
	err += boysGaussJacobiComp(22, 2.91371146222695857e+00, 1.37569333191435058e-03, errMarg);
	err += boysGaussJacobiComp(19, 3.16525550726132215e-02, 2.48805453513582370e-02, errMarg);
	err += boysGaussJacobiComp(12, 2.09417587700846377e+00, 5.81858736736084268e-03, errMarg);
	err += boysGaussJacobiComp(15, 2.87551358544984288e+00, 2.19750412249902217e-03, errMarg);
	err += boysGaussJacobiComp(11, 3.74357652003135060e-01, 3.08223366525322295e-02, errMarg);
	err += boysGaussJacobiComp(53, 2.97673095480940332e-01, 6.97777200019610124e-03, errMarg);
	err += boysGaussJacobiComp(65, 4.90397348342779461e+00, 6.11207175631414014e-05, errMarg);
	err += boysGaussJacobiComp(54, 4.17423983260431233e-01, 6.08929296295050040e-03, errMarg);
	err += boysGaussJacobiComp(62, 4.39994423618739994e-01, 5.18826594624253255e-03, errMarg);
	err += boysGaussJacobiComp(29, 1.57948604933454441e+00, 3.68331536266984844e-03, errMarg);
	err += boysGaussJacobiComp(77, 1.81879063121180401e+00, 1.07140877845038293e-03, errMarg);
	err += boysGaussJacobiComp(23, 4.63625162127909347e+00, 2.53872610366915764e-04, errMarg);
	err += boysGaussJacobiComp(51, 4.87568421409986594e-01, 6.01819053619613609e-03, errMarg);
	err += boysGaussJacobiComp(73, 2.84196161837828456e+00, 4.12398185135804522e-04, errMarg);
	err += boysGaussJacobiComp(85, 4.06475152021454688e+00, 1.05340615181350278e-04, errMarg);
	err += boysGaussJacobiComp(78, 2.13142635325963588e+00, 7.76662065115703828e-04, errMarg);
	err += boysGaussJacobiComp(14, 2.01830152382404778e-01, 2.85519604234165442e-02, errMarg);
	err += boysGaussJacobiComp(50, 7.29043849884289609e-01, 4.84450142459049873e-03, errMarg);
	err += boysGaussJacobiComp(24, 1.47664189263935161e+00, 4.94711045443220289e-03, errMarg);
	err += boysGaussJacobiComp(53, 4.16172462051881343e+00, 1.57633019307205248e-04, errMarg);
	err += boysGaussJacobiComp(22, 2.42623931680481501e+00, 2.18867058696143604e-03, errMarg);
	err += boysGaussJacobiComp(13, 1.10565025449478208e+00, 1.32653211100037921e-02, errMarg);
	err += boysGaussJacobiComp(49, 2.93905358850750125e+00, 5.67490889243916638e-04, errMarg);
	err += boysGaussJacobiComp(65, 2.22552675391620917e+00, 8.53041455156413569e-04, errMarg);
	err += boysGaussJacobiComp(88, 3.63491225768344867e+00, 1.55382545424575028e-04, errMarg);
	err += boysGaussJacobiComp(52, 7.29165391695675117e-01, 4.65689551703295511e-03, errMarg);
	err += boysGaussJacobiComp(12, 4.14640028555270438e+00, 9.02549877393784755e-04, errMarg);
	err += boysGaussJacobiComp(20, 3.99067842845876298e+00, 5.52451856943125083e-04, errMarg);
	err += boysGaussJacobiComp(16, 4.22737818308918280e+00, 5.79995569122797833e-04, errMarg);
	/* m = 0 .. 10, z= 5.000000e+00 .. 3.000000e+01 */
	err += boysGaussJacobiComp(7, 2.65299030717728560e+01, 1.96373873064420139e-08, errMarg);
	err += boysGaussJacobiComp(7, 1.27105157249199337e+01, 4.67820545465691176e-06, errMarg);
	err += boysGaussJacobiComp(9, 1.11230584738534261e+01, 4.99433178569089635e-06, errMarg);
	err += boysGaussJacobiComp(8, 5.37129458692201611e+00, 5.69739758450416983e-04, errMarg);
	err += boysGaussJacobiComp(1, 1.56312886945312452e+01, 7.17005428497372215e-03, errMarg);
	err += boysGaussJacobiComp(4, 1.07145123323015585e+01, 1.33348833937758246e-04, errMarg);
	err += boysGaussJacobiComp(1, 1.91059645713545582e+01, 5.30592958078778906e-03, errMarg);
	err += boysGaussJacobiComp(2, 2.08588016336415864e+01, 3.34489731491456038e-04, errMarg);
	err += boysGaussJacobiComp(3, 2.40110717976441027e+01, 2.44965985555732651e-05, errMarg);
	err += boysGaussJacobiComp(2, 1.05760917718943296e+01, 1.82584453104787371e-03, errMarg);
	err += boysGaussJacobiComp(4, 1.07517634824251921e+01, 1.31319923018956300e-04, errMarg);
	err += boysGaussJacobiComp(6, 1.00358282923656341e+01, 4.03172678289962034e-05, errMarg);
	err += boysGaussJacobiComp(0, 5.47892906868342847e+00, 3.78261480395963582e-01, errMarg);
	err += boysGaussJacobiComp(0, 1.36097073739555537e+01, 2.40226253436670254e-01, errMarg);
	err += boysGaussJacobiComp(5, 5.78760718891000480e+00, 1.01117939674783074e-03, errMarg);
	err += boysGaussJacobiComp(2, 2.37105717448630061e+01, 2.42801371668631682e-04, errMarg);
	err += boysGaussJacobiComp(3, 8.61958659153599469e+00, 8.69711577833474938e-04, errMarg);
	err += boysGaussJacobiComp(1, 1.75161748481979937e+01, 6.04443880924752762e-03, errMarg);
	err += boysGaussJacobiComp(7, 1.78005408144260599e+01, 3.90819942959252242e-07, errMarg);
	err += boysGaussJacobiComp(4, 1.60309583027948742e+01, 2.19893399718623621e-05, errMarg);
	err += boysGaussJacobiComp(1, 5.81891629977826995e+00, 3.12926689388285139e-02, errMarg);
	err += boysGaussJacobiComp(2, 2.23206874068650339e+01, 2.82382177734836615e-04, errMarg);
	err += boysGaussJacobiComp(3, 2.11111773917220969e+01, 3.84372594790543070e-05, errMarg);
	err += boysGaussJacobiComp(5, 1.78385193363418439e+01, 3.42981096851515732e-06, errMarg);
	err += boysGaussJacobiComp(0, 2.98533710073760069e+01, 1.62199029584505578e-01, errMarg);
	err += boysGaussJacobiComp(1, 1.37043093906448141e+01, 8.73428007209458796e-03, errMarg);
	err += boysGaussJacobiComp(0, 2.39053812214143036e+01, 1.81257966648478835e-01, errMarg);
	err += boysGaussJacobiComp(8, 9.33114880537891119e+00, 2.60490669849565536e-05, errMarg);
	err += boysGaussJacobiComp(0, 1.04258048892890095e+01, 2.74465643391503084e-01, errMarg);
	err += boysGaussJacobiComp(9, 1.65377357672650522e+01, 1.54776455775331250e-07, errMarg);
	err += boysGaussJacobiComp(2, 2.19722029227043184e+01, 2.93712338162186753e-04, errMarg);
	err += boysGaussJacobiComp(5, 2.64168048956758169e+01, 3.95808484621800808e-07, errMarg);
	err += boysGaussJacobiComp(8, 2.52388894296045645e+01, 8.48304110900746019e-09, errMarg);
	err += boysGaussJacobiComp(0, 9.98875844810448816e+00, 2.80405018534803785e-01, errMarg);
	err += boysGaussJacobiComp(1, 2.23679305265493216e+01, 4.18867087312500282e-03, errMarg);
	/* m = 10 .. 90, z= 5.000000e+00 .. 3.000000e+01 */
	err += boysGaussJacobiComp(70, 1.92245328618759941e+01, 4.33400554688531631e-11, errMarg);
	err += boysGaussJacobiComp(10, 9.89181912066122254e+00, 9.34026818696273425e-06, errMarg);
	err += boysGaussJacobiComp(30, 8.17974671103959913e+00, 6.18389295694653863e-06, errMarg);
	err += boysGaussJacobiComp(24, 7.52007969252186202e+00, 1.55939418218495283e-05, errMarg);
	err += boysGaussJacobiComp(89, 2.54189905423002868e+01, 7.08442441366052987e-14, errMarg);
	err += boysGaussJacobiComp(32, 1.06376081356388596e+01, 5.37769175151009233e-07, errMarg);
	err += boysGaussJacobiComp(73, 2.61650738841696614e+01, 4.52485888428729547e-14, errMarg);
	err += boysGaussJacobiComp(30, 1.92700054813983659e+01, 1.70373988628827959e-10, errMarg);
	err += boysGaussJacobiComp(42, 1.26468300154490580e+01, 5.31803587334539247e-08, errMarg);
	err += boysGaussJacobiComp(86, 2.97716788006918767e+01, 1.02714044786350082e-15, errMarg);
	err += boysGaussJacobiComp(74, 2.76356818783211442e+01, 1.04931031070858934e-14, errMarg);
	err += boysGaussJacobiComp(67, 1.62116123010556519e+01, 8.82570259643614001e-10, errMarg);
	err += boysGaussJacobiComp(63, 1.03306569323112328e+01, 3.05644793556233076e-07, errMarg);
	err += boysGaussJacobiComp(29, 6.17715921556351228e+00, 4.40421493459611961e-05, errMarg);
	err += boysGaussJacobiComp(70, 1.76084179953994054e+01, 2.11690286808927728e-10, errMarg);
	err += boysGaussJacobiComp(11, 5.97799067324183133e+00, 2.01532348445969970e-04, errMarg);
	err += boysGaussJacobiComp(27, 5.85183297777326192e+00, 6.56271926777048995e-05, errMarg);
	err += boysGaussJacobiComp(20, 1.68404763229879117e+01, 4.21895070541460645e-09, errMarg);
	err += boysGaussJacobiComp(67, 6.05435081778860514e+00, 1.90732660307018927e-05, errMarg);
	err += boysGaussJacobiComp(72, 1.23100354484967509e+01, 3.73100224549654081e-08, errMarg);
	err += boysGaussJacobiComp(83, 1.25057752602362257e+01, 2.60316364186279509e-08, errMarg);
	err += boysGaussJacobiComp(59, 6.33316826874109368e+00, 1.66693696353589451e-05, errMarg);
	err += boysGaussJacobiComp(24, 2.90446124234768099e+01, 7.42119974291119758e-14, errMarg);
	err += boysGaussJacobiComp(57, 6.69112892994784952e+00, 1.21902576280553909e-05, errMarg);
	err += boysGaussJacobiComp(62, 2.07665413465024307e+01, 1.13440730876788935e-11, errMarg);
	err += boysGaussJacobiComp(41, 1.70068185735957695e+01, 8.18101391457461557e-10, errMarg);
	err += boysGaussJacobiComp(70, 2.69520487045060350e+01, 2.23374125592427837e-14, errMarg);
	err += boysGaussJacobiComp(65, 1.11632755299639244e+01, 1.30055731097039240e-07, errMarg);
	err += boysGaussJacobiComp(31, 6.09577719352733688e+00, 4.39375873039425086e-05, errMarg);
	err += boysGaussJacobiComp(18, 1.64570399155563417e+01, 7.98505124997823672e-09, errMarg);
	err += boysGaussJacobiComp(11, 2.43251147381966542e+01, 6.82754680869066021e-10, errMarg);
	err += boysGaussJacobiComp(41, 5.21502235033788227e+00, 7.45982800292774695e-05, errMarg);
	err += boysGaussJacobiComp(20, 2.45659220513966159e+01, 6.98414431764812995e-12, errMarg);
	err += boysGaussJacobiComp(50, 9.75586608161083425e+00, 7.07177649909072579e-07, errMarg);
	err += boysGaussJacobiComp(11, 7.23138483724284237e+00, 6.81896973412850151e-05, errMarg);
	/* m = 90 .. 200, z= 0.000000e+00 .. 3.000000e+01 */
	err += boysGaussJacobiComp(108, 6.55555005167576446e+00, 6.97102008917135754e-06, errMarg);
	err += boysGaussJacobiComp(138, 6.66759831436095616e+00, 4.82038227900499749e-06, errMarg);
	err += boysGaussJacobiComp(112, 1.14988413593726942e+01, 5.01506867491939310e-08, errMarg);
	err += boysGaussJacobiComp(116, 4.56796400550042503e+00, 4.63465315929140115e-05, errMarg);
	err += boysGaussJacobiComp(139, 6.38578709196594329e+00, 6.32817193540230137e-06, errMarg);
	err += boysGaussJacobiComp(160, 7.37446306022909160e+00, 2.04690726067200503e-06, errMarg);
	err += boysGaussJacobiComp(106, 1.46404149411062849e+01, 2.38150680413150456e-09, errMarg);
	err += boysGaussJacobiComp(159, 1.66660991508910510e+01, 2.02205146218256831e-10, errMarg);
	err += boysGaussJacobiComp(114, 2.03525525968990355e+01, 7.67677644208968252e-12, errMarg);
	err += boysGaussJacobiComp(196, 6.40048424486130103e+00, 4.36734520934262999e-06, errMarg);
	err += boysGaussJacobiComp(118, 5.23602228046214460e+00, 2.34815673000039485e-05, errMarg);
	err += boysGaussJacobiComp(163, 1.06074954538447118e+01, 8.08372430578271002e-08, errMarg);
	err += boysGaussJacobiComp(94, 2.14515757471513257e+01, 3.29118466761506144e-12, errMarg);
	err += boysGaussJacobiComp(97, 8.96303687444297643e+00, 7.22367583152890804e-07, errMarg);
	err += boysGaussJacobiComp(124, 1.02727051007033680e+01, 1.51175936003237791e-07, errMarg);
	err += boysGaussJacobiComp(99, 1.02296009351812653e+01, 2.01861592793258461e-07, errMarg);
	err += boysGaussJacobiComp(98, 2.64192406530599626e+01, 2.31882622144869504e-14, errMarg);
	err += boysGaussJacobiComp(132, 2.25883086312445769e+01, 7.03310720988087134e-13, errMarg);
	err += boysGaussJacobiComp(146, 1.36934767097831084e+01, 4.25025708748869363e-09, errMarg);
	err += boysGaussJacobiComp(100, 3.17317419895544135e+00, 2.15031217342827884e-04, errMarg);
	err += boysGaussJacobiComp(109, 2.82247755365686974e+01, 3.38324192002785972e-15, errMarg);
	err += boysGaussJacobiComp(123, 1.40925053172813733e+01, 3.46035305938193238e-09, errMarg);
	err += boysGaussJacobiComp(109, 1.23992480930093206e+01, 2.11962423349140964e-08, errMarg);
	err += boysGaussJacobiComp(126, 3.27921757293449336e+00, 1.52773121743971348e-04, errMarg);
	err += boysGaussJacobiComp(167, 1.07110916453745925e+00, 1.02931379543230710e-03, errMarg);
	err += boysGaussJacobiComp(114, 2.88366489749167010e+00, 2.50485688367471183e-04, errMarg);
	err += boysGaussJacobiComp(98, 2.54578724506953317e+01, 5.98634516854993775e-14, errMarg);
	err += boysGaussJacobiComp(110, 2.21544084158236273e+00, 5.03695964233241741e-04, errMarg);
	err += boysGaussJacobiComp(145, 1.73317578758603899e+01, 1.15784193417679468e-10, errMarg);
	err += boysGaussJacobiComp(170, 7.85351293212905868e+00, 1.19360309611942457e-06, errMarg);
	err += boysGaussJacobiComp(128, 7.42899264236361151e+00, 2.45098867135004395e-06, errMarg);
	err += boysGaussJacobiComp(176, 1.59979455797387281e+01, 3.51076933075999839e-10, errMarg);
	err += boysGaussJacobiComp(100, 2.15376165876964989e+00, 5.89861110120164300e-04, errMarg);
	err += boysGaussJacobiComp(186, 2.14998208547183632e+01, 1.39280972402024329e-12, errMarg);
	err += boysGaussJacobiComp(140, 3.26552015899235240e+00, 1.39070383439031829e-04, errMarg);
	return err;
} /* main */
